import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full flex justify-center items-center">
            <p className="font-semibold text-red-400 text-3xl">
                Hello from Vercel!
            </p>
        </div>
      </main>
    </>
  )
}
